require 'active_support/all'
require 'rspec'
require 'pry'
require 'JSON'
require 'CSV'

require File.dirname(__FILE__) + '/../../models/customer'
require File.dirname(__FILE__) + '/../../models/customers'
require File.dirname(__FILE__) + '/../../models/csv_parser'
require File.dirname(__FILE__) + '/../../models/db_accessor'
